/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.41
 * Generated at: 2021-07-04 16:58:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <title>Resturant Website Design </title>\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\" integrity=\"sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("   \r\n");
      out.write("   <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write(" <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Dancing+Script&family=Indie+Flower&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js\" integrity=\"sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("   <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("function usersingin()\r\n");
      out.write("{\r\n");
      out.write("\talert(\"doing singin\");\r\n");
      out.write("\tdocument.myform.action=\"singin\";\r\n");
      out.write("\tdocument.myform.submit();\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("function usersingup()\r\n");
      out.write("{\r\n");
      out.write("\talert(\"doing singup\");\r\n");
      out.write("\tdocument.myform.action=\"singup\";\r\n");
      out.write("\tdocument.myform.submit();\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script> \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- header section starts -->\r\n");
      out.write("\r\n");
      out.write("<header id=\"header\">\r\n");
      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li><a href=\"#home\">home</a></li>\r\n");
      out.write("        <li><a href=\"#special\">special</a></li>\r\n");
      out.write("        <li><a href=\"#about\">about</a></li>\r\n");
      out.write("        <li><a href=\"#dish\">dishes</a></li>\r\n");
      out.write("        <li><a href=\"#contact\">contact</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"fas fa-hamburger\"></div>\r\n");
      out.write("\r\n");
      out.write("<a href=\"#\" class=\"logo\"><img src=\"C:\\Users\\india\\Desktop\\logo.jpg\" alt=\"\"></a>\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!-- header section ends -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- home section starts  -->\r\n");
      out.write("\r\n");
      out.write("<section id=\"home\" class=\"container-fluid\">\r\n");
      out.write("<div class=\"row min-vh-100 align-items-center\">\r\n");
      out.write("    \r\n");
      out.write("<div class=\"col-md-8 ml-md-5 text-md-left text-center content\">\r\n");
      out.write("    <h1>food that you can't resist</h1>\r\n");
      out.write("    <h2>enjoy the marvelous taste</h2>\r\n");
      out.write("    <p>Wel-Come TO Food Lovers Hub</p>\r\n");
      out.write("    <a href=\"#special\"><button>get started</button></a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"video-container\">\r\n");
      out.write("    <video src=\"C:\\Users\\india\\Desktop\\vid1.mp4\" autoplay loop class=\"vid vid1\"></video>\r\n");
      out.write("    <video src=\"C:\\Users\\india\\Desktop\\vid2.mp4\" autoplay loop class=\"vid vid2\"></video>\r\n");
      out.write("    <video src=\"C:\\Users\\india\\Desktop\\vid3.mp4\" autoplay loop class=\"vid vid3\"></video>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"controls\">\r\n");
      out.write("    <div class=\"dots dot1\"></div>\r\n");
      out.write("    <div class=\"dots dot2\"></div>\r\n");
      out.write("    <div class=\"dots dot3\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- home section ends  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- special card section starts  -->\r\n");
      out.write("\r\n");
      out.write("<section id=\"special\" class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"heading text-center\">\r\n");
      out.write("<h1>our <span>special</span></h1>\r\n");
      out.write("<p>Daily Special Items Prepared For Customer Suggestions</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"card-container\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <img src=\"C:\\Users\\india\\Desktop\\image26.jpg\" alt=\"\">\r\n");
      out.write("        <p>Its A Maharashtra Special Ukadiche Modak (Indain Momos))   </p>\r\n");
      out.write("        <a href=\"#\"><button>read more</button></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <img src=\"C:\\Users\\india\\Desktop\\image16.jpg\" alt=\"\">\r\n");
      out.write("        <p>Its A Special Punjabi Biryani Its Cooking As Traditional Way You Enjoy it.</p>\r\n");
      out.write("        <a href=\"#\"><button>read more</button></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <img src=\"C:\\Users\\india\\Desktop\\image9.jpg\" alt=\"\">\r\n");
      out.write("        <p>South Indian Special ChijDosa</p>\r\n");
      out.write("        <a href=\"#\"><button>read more</button></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- special card section ends  -->\r\n");
      out.write("\r\n");
      out.write("<!-- about section starts  -->\r\n");
      out.write("\r\n");
      out.write("<section id=\"about\" class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"heading text-center\">\r\n");
      out.write("    <h1><span>about</span> us</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row min-vh-100\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-6 text-center text-md-left align-self-center content\">\r\n");
      out.write("            <p>Everything began in 1946 when the proprietor opened his first espresso and doughnut and sandwich shop. </p>\r\n");
      out.write("            <p>It was gigantically fruitful and this driven him to begin another shop called organization name. He opened the principal store in 1950 in Massachusetts in the USA.</p>\r\n");
      out.write("            <a href=\"#\"><button>learn more</button></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div align=\"center\" class=\"col-md-6 image\" >\r\n");
      out.write("            <img src=\"C:\\Users\\india\\Desktop\\image11.jpg\" alt=\"\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- about section ends  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- dish section starts  -->\r\n");
      out.write("\r\n");
      out.write("<section id=\"dish\" class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"heading text-center\">\r\n");
      out.write("        <h1>our <span>dishes</span></h1>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"box-container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"box\">\r\n");
      out.write("            <img src=\"C:\\Users\\india\\Desktop\\image4.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"info\">\r\n");
      out.write("                <h3>dish1</h3>\r\n");
      out.write("                <p>The One And Only Mumbai Special PavBhaji</p>\r\n");
      out.write("                <a href=\"#\"><button>view</button></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"box\">\r\n");
      out.write("            <img src=\"C:\\Users\\india\\Desktop\\image1.png\" alt=\"\">\r\n");
      out.write("            <div class=\"info\">\r\n");
      out.write("                <h3>dish2</h3>\r\n");
      out.write("                <p>French Fries With Spices</p>\r\n");
      out.write("                <a href=\"#\"><button>view</button></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"box\">\r\n");
      out.write("            <img src=\"C:\\Users\\india\\Desktop\\image2.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"info\">\r\n");
      out.write("                <h3>dish3</h3>\r\n");
      out.write("                <p>HamBuerger Combo</p>\r\n");
      out.write("                <a href=\"#\"><button>view</button></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"box\">\r\n");
      out.write("            <img src=\"C:\\Users\\india\\Desktop\\image15.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"info\">\r\n");
      out.write("                <h3>dish4</h3>\r\n");
      out.write("                <p>Spicy Misal Pav</p>\r\n");
      out.write("                <a href=\"#\"><button>view</button></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"box\">\r\n");
      out.write("            <img src=\"C:\\Users\\india\\Desktop\\image17.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"info\">\r\n");
      out.write("                <h3>dish5</h3>\r\n");
      out.write("                <p>South Indian Idle  </p>\r\n");
      out.write("                <a href=\"#\"><button>view</button></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"box\">\r\n");
      out.write("            <img src=\"C:\\Users\\india\\Desktop\\image18.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"info\">\r\n");
      out.write("                <h3>dish6</h3>\r\n");
      out.write("                <p>Chinese Noodles</p>\r\n");
      out.write("                <a href=\"#\"><button>view</button></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      <div class=\"box\">\r\n");
      out.write("            <img src=\"C:\\Users\\india\\Desktop\\image13.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"info\">\r\n");
      out.write("                <h3>dish7</h3>\r\n");
      out.write("                <p>Italian Pasta</p>\r\n");
      out.write("                <a href=\"#\"><button>view</button></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>  \r\n");
      out.write("        \r\n");
      out.write("<div class=\"box\">\r\n");
      out.write("            <img src=\"C:\\Users\\india\\Desktop\\image24.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"info\">\r\n");
      out.write("                <h3>dish8</h3>\r\n");
      out.write("                <p>Malie Kofta</p>\r\n");
      out.write("                <a href=\"#\"><button>view</button></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"box\">\r\n");
      out.write("            <img src=\"C:\\Users\\india\\Desktop\\image22.jpg\" alt=\"\">\r\n");
      out.write("            <div class=\"info\">\r\n");
      out.write("                <h3>dish9</h3>\r\n");
      out.write("                <p>Fast Food ComBo</p>\r\n");
      out.write("                <a href=\"#\"><button>view</button></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- dish section ends  -->\r\n");
      out.write("\r\n");
      out.write("<!-- contact section starts  -->\r\n");
      out.write("\r\n");
      out.write("<section id=\"contact\" class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"heading text-center\">\r\n");
      out.write("        <h1><span>contact</span> us</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("        <form action=\"\" class=\"col-md-7\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"inputBox\">\r\n");
      out.write("                <input type=\"text\" required>\r\n");
      out.write("                <h3>full name</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"inputBox\">\r\n");
      out.write("                <input type=\"email\" required>\r\n");
      out.write("                <h3>e-mail</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"inputBox\">\r\n");
      out.write("                <textarea required name=\"\" id=\"\" cols=\"30\" rows=\"10\"></textarea>\r\n");
      out.write("                <h3>message</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <input type=\"submit\" value=\"send\">\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- contact section ends  -->\r\n");
      out.write("\r\n");
      out.write("<!-- footer section starts  -->\r\n");
      out.write("\r\n");
      out.write("<section id=\"footer\" class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"row align-items-center\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-4 brand\">\r\n");
      out.write("\r\n");
      out.write("<a href=\"#\" class=\"logo\"><img src=\"C:\\Users\\india\\Desktop\\logo.jpg\" alt=\"\"></a>\r\n");
      out.write("\r\n");
      out.write("<div class=\"icons\">\r\n");
      out.write("    <a href=\"#\" class=\"fab fa-facebook-square\"></a>\r\n");
      out.write("    <a href=\"#\" class=\"fab fa-twitter-square\"></a>\r\n");
      out.write("    <a href=\"#\" class=\"fab fa-instagram-square\"></a>\r\n");
      out.write("    <a href=\"#\" class=\"fab fa-pinterest-square\"></a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-4 footer-links\">\r\n");
      out.write("<h3>links:</h3>\r\n");
      out.write("<a href=\"#home\">home</a>\r\n");
      out.write("<a href=\"#special\">special</a>\r\n");
      out.write("<a href=\"#about\">about</a>\r\n");
      out.write("<a href=\"#dish\">dish</a>\r\n");
      out.write("<a href=\"#contact\">contact</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-4 text-center text-md-left letter\">\r\n");
      out.write("<h2>newsletter</h2>\r\n");
      out.write("<input type=\"text\"><br>\r\n");
      out.write("<input type=\"submit\" value=\"subscribe\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-11 text-center text-md-right letter\">\r\n");
      out.write("\r\n");
      out.write("<form name=\"myform\" >\r\n");
      out.write("\r\n");
      out.write("<h2><font color=\"red\">Wel-Come To FOODIES SHOP </font></h2>\r\n");
      out.write("<input type=\"button\"   value=\"CustomerLogin\" class=\"btn btn-primary\" onclick=\"usersingin()\">\r\n");
      out.write("<input type=\"button\"   value=\"Employeesingup\" class=\"btn btn-primary\" onclick=\"usersingup()\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<h1>&copy; copyright @ 2021 by <span>Mr.Me</span></h1>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- footer section ends  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- script part starts  -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("    $('.fa-hamburger').click(function(){\r\n");
      out.write("        $(this).toggleClass('fa-times');\r\n");
      out.write("        $('nav').toggleClass('nav-toggle');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $('nav ul li a').click(function(){\r\n");
      out.write("        $('.fa-hamburger').removeClass('fa-times');\r\n");
      out.write("        $('nav').removeClass('nav-toggle');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $('.dot1').click(function(){\r\n");
      out.write("        $('.vid1').css('display','block');\r\n");
      out.write("        $('.vid2').css('display','none');\r\n");
      out.write("        $('.vid3').css('display','none');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $('.dot2').click(function(){\r\n");
      out.write("        $('.vid2').css('display','block');\r\n");
      out.write("        $('.vid1').css('display','none');\r\n");
      out.write("        $('.vid3').css('display','none');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $('.dot3').click(function(){\r\n");
      out.write("        $('.vid3').css('display','block');\r\n");
      out.write("        $('.vid1').css('display','none');\r\n");
      out.write("        $('.vid2').css('display','none');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    $(window).on('scroll load',function(){\r\n");
      out.write("        if($(window).scrollTop() > 10){\r\n");
      out.write("            $('#header').addClass('header-active');\r\n");
      out.write("        }else{\r\n");
      out.write("            $('#header').removeClass('header-active');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
